# Site settings
name: Your awesome site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-theme" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Google Analytics
#google_analytics_tracking_id: "UA-XXXXXXXX-X" # Your Google Analytics ID

permalink: /blog/:year/:month/:day/:title/

# disqus configurations
disqus: true
disqus_shortname: 'isammocsjekylltheme'

author:
  name: Your Name Here # *Required* Display name of the author
  description: > # this means to ignore newlines until email:
    A short bio to explains who you are and what are your expert domains.
  email: your.name@example.com # Email address of the author
  avatar: http://images.clipartlogo.com/files/ss/thumb/920/92073038/avatar-with-blank-question-mark_small.jpg
  uri: http://blog.example.com # Webpage where more information about the author can be found
  social:
    - title: github
      url: https://github.com/Isammoc/jekyll-theme
    - title: twitter
      url: https://twitter.com/isammoc ## TODO


# jekyll-feed configurations
#feed:
#  path: feed.xml

# Build settings
markdown: redcarpet

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
